repos:
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.1.2
    hooks:
      - id: betterleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
        types: [sh]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt
        args: ["-i", "2", "-s", "-bn"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint"]
        types: [yaml]
  - repo: local
    hooks:
      - id: deno-fmt
        name: deno fmt
        entry: deno fmt --check
        language: system
        types_or: [javascript]
        files: '\.mjs$'
      - id: deno-lint
        name: deno lint
        entry: deno lint
        language: system
        types_or: [javascript]
        files: '\.mjs$'
